import { type Resource } from './types'

const CATEGORIES = ['All', 'Websites', 'Libraries', 'Tools', 'People']

const SUBCATEGORIES = {
  Websites: ['Learning', 'Immersive', 'Polished', 'Inspirations', 'Open Source'],
  Libraries: ['Animation', 'User Interface'],
  Tools: ['Productivity', 'Development'],
  People: ['Developers', 'Designers', 'Educators', 'Indie Hackers'],
}

const RESOURCES: Resource[] = [
  {
    name: 'Awwwards',
    description: 'Definitive inspiration resource for digital creatives.',
    url: 'https://www.awwwards.com/',
    category: 'Websites',
    subcategory: 'Inspirations',
  },
  {
    name: 'Rauno Freiberg',
    description: 'Design Engineer at Vercel.',
    url: 'https://rauno.me/',
    category: 'People',
    subcategory: 'Developers',
  },
  {
    name: 'Godly',
    description: 'Hand-picked design inspiration.',
    url: 'https://godly.website/',
    category: 'Websites',
    subcategory: 'Inspirations',
  },
  {
    name: 'Taxonomy',
    description: 'Next.js 13 with server components example app.',
    url: 'https://tx.shadcn.com/',
    category: 'Websites',
    subcategory: 'Open Source',
  },
  {
    name: 'Raycast',
    description: 'Spotlight on steroids with AI.',
    url: 'https://raycast.com/',
    category: 'Tools',
    subcategory: 'Productivity',
  },
  {
    name: 'Build UI',
    description: 'Master Framer Motion & Tailwind CSS with Sam.',
    url: 'https://buildui.com/',
    category: 'Websites',
    subcategory: 'Learning',
  },
  {
    name: 'Lenis',
    description: 'How smooth scroll should be.',
    url: 'https://lenis.studiofreight.com/',
    category: 'Libraries',
    subcategory: 'Animation',
  },
  {
    name: 'Scrollytelling',
    description: 'Scroll-driven animations with React & GSAP.',
    url: 'https://scrollytelling.basement.studio/',
    category: 'Libraries',
    subcategory: 'Animation',
  },
  {
    name: 'Sonner',
    description: 'An opinionated toast component for React.',
    url: 'https://sonner.emilkowal.ski/',
    category: 'Libraries',
    subcategory: 'User Interface',
  },
  {
    name: 'Vaul',
    description: 'Mobile-friendly drawer component for React.',
    url: 'https://vaul.emilkowal.ski/',
    category: 'Libraries',
    subcategory: 'User Interface',
  },
  {
    name: 'Framer Motion',
    description: 'A motion library for React.',
    url: 'https://www.framer.com/motion/',
    category: 'Libraries',
    subcategory: 'Animation',
  },
  {
    name: 'GSAP',
    description: 'JavaScript animation library.',
    url: 'https://gsap.com/',
    category: 'Libraries',
    subcategory: 'Animation',
  },
  {
    name: 'Fig',
    description: 'Add autocomplete to your terminal.',
    url: 'https://fig.io/',
    category: 'Tools',
    subcategory: 'Development',
  },
  {
    name: 'Warp',
    description: 'Good looking terminal.',
    url: 'https://warp.dev/',
    category: 'Tools',
    subcategory: 'Development',
  },
  {
    name: 'Josh tried coding',
    description: 'Talking about latest web stuff.',
    url: 'https://www.youtube.com/@joshtriedcoding',
    category: 'People',
    subcategory: 'Educators',
  },
  {
    name: 'Devon Govett',
    description: 'Creator of Parcel. Working on React Aria at Adobe.',
    url: 'https://twitter.com/devongovett',
    category: 'People',
    subcategory: 'Developers',
  },
  {
    name: 'Pieter Levels',
    description: 'The most famous Indie Hacker.',
    url: 'https://twitter.com/levelsio',
    category: 'People',
    subcategory: 'Indie Hackers',
  },
  {
    name: 'Pedro Duarte',
    description: 'DX Engineer at Raycast. Radix UI & Stitches.',
    url: 'https://ped.ro/',
    category: 'People',
    subcategory: 'Developers',
  },
  {
    name: 'Chris Kalafatis',
    description: 'One of my favorite portfolios.',
    url: 'https://chriskalafatis.com/',
    category: 'Websites',
    subcategory: 'Immersive',
  },
  {
    name: 'Kevin Powell',
    description: 'The CSS King.',
    url: 'https://www.youtube.com/user/KepowOb',
    category: 'People',
    subcategory: 'Educators',
  },
  {
    name: 'Cal.com',
    description: 'The open source Calendly alternative.',
    url: 'https://cal.com/',
    category: 'Websites',
    subcategory: 'Open Source',
  },
  {
    name: 'Tremor',
    description: 'Build dashboards fast with Tailwind CSS.',
    url: 'https://www.tremor.so/',
    category: 'Libraries',
    subcategory: 'User Interface',
  },
  {
    name: 'Radix UI',
    description: 'Accessible UI components for React.',
    url: 'https://www.radix-ui.com/',
    category: 'Libraries',
    subcategory: 'User Interface',
  },
  {
    name: 'React Aria',
    description: 'Accessible UI components for React.',
    url: 'https://react-spectrum.adobe.com/react-aria/examples/index.html',
    category: 'Libraries',
    subcategory: 'User Interface',
  },
  {
    name: 'Draft UI',
    description: 'React Aria Components with Tailwind CSS.',
    url: 'https://draft-ui.com/',
    category: 'Libraries',
    subcategory: 'User Interface',
  },
  {
    name: 'React Wrap Balancer',
    description: 'Avoids single hanging word on the last line.',
    url: 'https://react-wrap-balancer.vercel.app/',
    category: 'Libraries',
    subcategory: 'User Interface',
  },
  {
    name: '⌘K',
    description: 'Fast, composable, unstyled command menu for React.',
    url: 'https://cmdk.paco.me/',
    category: 'Libraries',
    subcategory: 'User Interface',
  },
  {
    name: 'Paco Coursey',
    description: 'Design Engineer at Linear.',
    url: 'https://paco.me/',
    category: 'People',
    subcategory: 'Developers',
  },
  {
    name: 'Emil Kowalski',
    description: 'Design Engineer at Vercel.',
    url: 'https://emilkowal.ski//',
    category: 'People',
    subcategory: 'Developers',
  },
  {
    name: 'Josh W. Comeau',
    description: 'High quality courses for developers.',
    url: 'https://www.joshwcomeau.com/',
    category: 'People',
    subcategory: 'Educators',
  },
  {
    name: 'Lee Robinson',
    description: 'VP of Product at Vercel.',
    url: 'https://leerob.io/',
    category: 'People',
    subcategory: 'Developers',
  },
  {
    name: 'Delba de Oliveira',
    description: 'DX at Vercel.',
    url: 'https://delba.dev',
    category: 'People',
    subcategory: 'Developers',
  },
  {
    name: 'dnd kit',
    description: 'Drag & Drop toolkit for React.',
    url: 'https://dndkit.com/',
    category: 'Libraries',
    subcategory: 'User Interface',
  },
  {
    name: 'Tiptap',
    description: 'Customizable rich text WYSIWYG editor.',
    url: 'https://tiptap.dev/editor/',
    category: 'Libraries',
    subcategory: 'User Interface',
  },
  {
    name: 'Jack Herrington',
    description: 'Talking about latest web stuff.',
    url: 'https://www.youtube.com/@jherr',
    category: 'People',
    subcategory: 'Educators',
  },
  {
    name: 'Web Dev Simplified',
    description: 'Great tutorials for beginners.',
    url: 'https://www.youtube.com/@WebDevSimplified',
    category: 'People',
    subcategory: 'Educators',
  },
  {
    name: 'Lusion',
    description: `Probably the best website I've ever seen.`,
    url: 'https://lusion.co/',
    category: 'Websites',
    subcategory: 'Immersive',
  },
  {
    name: 'Zero',
    description: 'Typical Web3 website with fancy animations.',
    url: 'https://zero.tech/',
    category: 'Websites',
    subcategory: 'Immersive',
  },
  {
    name: 'Bruno Simon',
    description: 'The one and only Three.js master.',
    url: 'https://bruno-simon.com/',
    category: 'Websites',
    subcategory: 'Immersive',
  },
  {
    name: 'ColorSlurp',
    description: 'Best color picker for macOS.',
    url: 'https://colorslurp.com/',
    category: 'Tools',
    subcategory: 'Productivity',
  },
  {
    name: 'ui.land',
    description: 'The Digital Library for designers and engineers.',
    url: 'https://ui.land/',
    category: 'Websites',
    subcategory: 'Inspirations',
  },
  {
    name: 'Learn Next.js',
    description: 'Learn foundations of Next.js with latest features.',
    url: 'https://nextjs.org/learn',
    category: 'Websites',
    subcategory: 'Learning',
  },
  {
    name: 'Matt Pocock',
    description: 'TypeScript guru.',
    url: 'https://twitter.com/mattpocockuk',
    category: 'People',
    subcategory: 'Educators',
  },
  {
    name: 'Kent C. Dodds',
    description: 'The best React educator out there.',
    url: 'https://kentcdodds.com/',
    category: 'People',
    subcategory: 'Educators',
  },
  {
    name: 'Jhey Tompkins',
    description: 'CSS animation god. DX Engineer at Vercel.',
    url: 'https://twitter.com/jh3yy',
    category: 'People',
    subcategory: 'Developers',
  },
  {
    name: 'Aristide Benoist',
    description: 'One of the best creative developers.',
    url: 'https://twitter.com/AristideBenoist',
    category: 'People',
    subcategory: 'Developers',
  },
  {
    name: 'Alex Frison de Isla',
    description: 'Specializes in motion and interaction.',
    url: 'https://twitter.com/AlexFisla',
    category: 'People',
    subcategory: 'Developers',
  },
  {
    name: 'Locomotive',
    description: '5 times Awwwards Agency of the Year.',
    url: 'https://locomotive.ca/en',
    category: 'Websites',
    subcategory: 'Immersive',
  },
  {
    name: 'Codrops',
    description: 'A collection of tutorials for creative developers.',
    url: 'https://tympanus.net/codrops/',
    category: 'Websites',
    subcategory: 'Inspirations',
  },
  {
    name: 'This Week In React',
    description: 'Probably the best React newsletter.',
    url: 'https://thisweekinreact.com/',
    category: 'Websites',
    subcategory: 'Learning',
  },
  {
    name: 'OKAY dev',
    description: 'A community for creative developers.',
    url: 'https://okay.dev/',
    category: 'Websites',
    subcategory: 'Inspirations',
  },
  {
    name: 'Linear',
    description: 'Trendsetter in the clean and polished websites.',
    url: 'https://linear.app/',
    category: 'Websites',
    subcategory: 'Polished',
  },
  {
    name: 'Fey',
    description: 'Love their app design.',
    url: 'https://www.feyapp.com/',
    category: 'Websites',
    subcategory: 'Polished',
  },
  {
    name: 'Diagram',
    description: 'Check those micro-animations!',
    url: 'https://diagram.com/',
    category: 'Websites',
    subcategory: 'Polished',
  },
  {
    name: 'Wope',
    description: 'Inspired by Linear but really great in its own way.',
    url: 'https://wope.com/',
    category: 'Websites',
    subcategory: 'Polished',
  },
  {
    name: 'CSS Design Awards',
    description: 'Web awards for digital creatives.',
    url: 'https://www.cssdesignawards.com/',
    category: 'Websites',
    subcategory: 'Inspirations',
  },
  {
    name: 'Times Two',
    description: 'Can we talk about their bottom menu?',
    url: 'https://timestwo.design/',
    category: 'Websites',
    subcategory: 'Immersive',
  },
  {
    name: 'Atlas',
    description: 'Beautiful & clean landing page.',
    url: 'https://atlascard.com/',
    category: 'Websites',
    subcategory: 'Polished',
  },
  {
    name: 'Ilya Miskov',
    description: 'Human Interface Designer at Whop.',
    url: 'https://twitter.com/ilyamiskov',
    category: 'People',
    subcategory: 'Designers',
  },
  {
    name: 'Steven Tey',
    description: 'Multiple OSS projects. Working at Vercel.',
    url: 'https://twitter.com/steventey',
    category: 'People',
    subcategory: 'Developers',
  },
  {
    name: 'Three.js Journey',
    description: 'Everything you need to know about Three.js.',
    url: 'https://threejs-journey.com/',
    category: 'Websites',
    subcategory: 'Learning',
  },
  {
    name: 'Oğuz Yağız Kara',
    description: 'Designer at WorkOS.',
    url: 'https://twitter.com/oguzyagizkara',
    category: 'People',
    subcategory: 'Designers',
  },
  {
    name: 'James',
    description: 'Design Lead at Clerk.',
    url: 'https://twitter.com/jamesm',
    category: 'People',
    subcategory: 'Designers',
  },
  {
    name: 'AuthKit',
    description: 'Clean & polished landing page with great animations.',
    url: 'https://www.authkit.com/',
    category: 'Websites',
    subcategory: 'Polished',
  },
]

export { CATEGORIES, SUBCATEGORIES, RESOURCES }
